"""UI theme constants for HydroBuddy."""

FONT_FAMILY = "Segoe UI"
FONT_SIZE_SMALL = 9
FONT_SIZE_NORMAL = 10
FONT_SIZE_LARGE = 13
FONT_SIZE_TITLE = 15

COLOR_WINDOW_BACKGROUND = "#EAF7FF"
COLOR_WINDOW_BORDER = "#8ACDEB"
COLOR_CHARACTER_BACKGROUND = "#D7F1FF"
COLOR_CHARACTER_BORDER = "#7CB9D3"
COLOR_CHARACTER_TEXT = "#256078"
COLOR_SPEECH_BUBBLE = "#FFFFFF"
COLOR_SPEECH_BORDER = "#B5DCEB"
COLOR_SPEECH_TITLE = "#153747"
COLOR_SPEECH_SUBTITLE = "#486575"
COLOR_BUTTON_PRIMARY = "#2F80ED"
COLOR_BUTTON_SECONDARY = "#EDF5F9"
COLOR_BUTTON_PRIMARY_TEXT = "#FFFFFF"
COLOR_BUTTON_SECONDARY_TEXT = "#264653"
COLOR_BUTTON_BORDER = "#A7CFDF"
COLOR_SETTINGS_BACKGROUND = "#F7FBFD"
COLOR_SETTINGS_TEXT = "#172A3A"
COLOR_SETTINGS_FIELD_BACKGROUND = "#FFFFFF"
COLOR_SETTINGS_FIELD_TEXT = "#172A3A"
COLOR_SETTINGS_FIELD_BORDER = "#9BB8C7"
COLOR_SETTINGS_BUTTON_BACKGROUND = "#EAF2F7"
COLOR_SETTINGS_BUTTON_TEXT = "#172A3A"
COLOR_SETTINGS_BUTTON_BORDER = "#8FAEBD"
COLOR_SETTINGS_BUTTON_PRESSED = "#D8E8F0"
COLOR_SETTINGS_CHECK_INDICATOR = "#FFFFFF"

BUTTON_WIDTH = 148
BUTTON_HEIGHT = 38
BUTTON_GAP = 10

CORNER_RADIUS_SMALL = 6
CORNER_RADIUS_MEDIUM = 10
CORNER_RADIUS_LARGE = 18

SPACING_SMALL = 6
SPACING_MEDIUM = 12
SPACING_LARGE = 18
SPACING_XLARGE = 24

BUBBLE_PADDING_HORIZONTAL = 18
BUBBLE_PADDING_VERTICAL = 12

WINDOW_WIDTH = 340
WINDOW_HEIGHT = 330
WINDOW_MARGIN = 24

SPEECH_BUBBLE_WIDTH = 292
SPEECH_BUBBLE_MIN_HEIGHT = 86

ANIMATION_PLACEHOLDER_WIDTH = 180
ANIMATION_PLACEHOLDER_HEIGHT = 140

FADE_DURATION_MS = 200

SETTINGS_WIDTH = 420
SETTINGS_FIELD_WIDTH = 150
